### ISSUE TITLE
Light name

### ISSUE THREAD

**Issue by stefano055415** [jakubdybczak/esp32-arduino-matter#11]
@jakubdybczak

Can I set a default name to the light when for example I pair it with the apple home app

**Comment by jakubdybczak** [comment]
Hey, I don't know if there is such possibility. When I test this library with Google Home app it's asking me to type unique device name - there is no default name. Maybe Apple Home have some default names for each device type?

**Comment by SCratORS** [comment]
HomeAssistant  using default name "TEST_PRODUCT" for all endpoints, and node name as "TEST_VENDOR"... 
this is very inconvenient if there are a lot of endpoints....
TEST_PRODUCT_1
TEST_PRODUCT_2
TEST_PRODUCT_3
...etc
Try to guess which one is responsible for what....
