### ISSUE TITLE
Matter.h: No such file or directory

### ISSUE THREAD

**Issue by LukasAV** [jakubdybczak/esp32-arduino-matter#6]
Hi,
I am getting the following error when trying to build. I feel like I am missing something obvious, but unfortunately I could not figure it out yet.
![image](https://user-images.githubusercontent.com/41890101/205917611-f8a390ab-ecc7-4623-aeb2-f06501dc06f9.png)
This is my project structure, I copied the `Light.ino` in the main.cpp, the library got cloned from git correctly
![image](https://user-images.githubusercontent.com/41890101/205917965-755bed05-b613-4d31-b624-cafa93afe2cb.png)
`platformio.ini`:
```
[env:nodemcu-32s]
platform = espressif32
board = esp32dev
framework = espidf
build_unflags=-std=gnu++11
build_flags=-std=gnu++17
lib_deps = https://github.com/jakubdybczak/esp32-arduino-matter.git
board_build.partitions = partitions_singleapp_large.csv
```

**Comment by oleksiikutuzov** [comment]
I guess `framework` should be `arduino`. Mine works fine with this setup: https://github.com/oleksiikutuzov/esp32-matter-switch/blob/main/platformio.ini

**Comment by LukasAV** [comment]
Thank you so much, I knew it was something stupid. I confused the framework with the platform.
Now it built without issues.
